### ISSUE TITLE
Can you kindly add CmakeLists file

### ISSUE THREAD

**Issue by Longwater1234** [mustafaquraish/rt#11]
Hi, thanks for creating this library. Could you kindly add a CmakeLists file please so it can be built cross platform?  Also can you show sample usage of this library?

**Comment by mustafaquraish** [comment]
This is meant to be a standalone CLI application, not a library. That being said, you can possibly extract some of the parts to work in isolation, but this project isn't something I'm working on anymore and so will leave that to you. PRs are welcome if you end up making any changes
